version: "3.8"
services:
 
    redis:
        image: redis:latest
        container_name: 'redis'
        ports: 
            - "9991:6379"
        volumes:
            - ./redis:/usr/local/etc/redis
        networks:
            - padrão
    networks:
        padrão:
            driver: bridge